version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./chat-link-stream
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./chat-link-stream:/app
      - /app/node_modules
    restart: unless-stopped

  # Optional: Redis for production session storage
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
