version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-change-this-in-production
      - HOST=0.0.0.0
      - PORT=8081
      - FLASK_DEBUG=True
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./chat-link-stream
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8081
      - VITE_SOCKET_URL=http://localhost:8081
    depends_on:
      - backend
    volumes:
      - ./chat-link-stream:/app
      - /app/node_modules
    restart: unless-stopped

  # Optional: Redis for production session storage
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
